### PR TITLE
': command' take 2

### PR DESCRIPTION
**Pull request by orefalo**
had many conflicts to fix manually,
hope it did it well.

### CODE REVIEW

**Comment by laurence-flwls** [comment]
Looks good. One quick question though, was this an intentional formatting change or something your IDE autocorrected?
https://github.com/lmorg/murex/pull/686/files#diff-89bf90418f3bc62b338720a4101b88268d833f94fbf75dd026d99b78790e2a78L142-R142

**Comment by lmorg** [comment]
Looks good. One quick question though, was this an intentional formatting change or something your IDE autocorrected?
https://github.com/lmorg/murex/pull/686/files#diff-89bf90418f3bc62b338720a4101b88268d833f94fbf75dd026d99b78790e2a78L142-R142

**Comment by orefalo** [comment]
My IDE (visual studio) - auto formatted all yaml and md files I opened

**Comment by lmorg** [comment]
Should be fine. The markdown was formatted for readability in the command line (because the md files are compiled into the shell). But I don't any of the changes dramatically affect that. More just define a different set of opinionated formatting options. Which is fine.

Thanks for PR. I'll get that merged shortly

**Pull request merged**
