### PR TITLE
fix: CTRL+K erases from cursor onward

### PR DESCRIPTION
**Pull request by orefalo**
First.. tiny tiny contribution... ;-)

CTRL+K erases from cursor onward

### CODE REVIEW

**Comment by lmorg** [comment]
Thanks for the PR. Just had a play with this and it appears to delete the character before the cursor. Was that expected? If not, which OS and terminal are you using?

image
^ cursor under `6` (before `ctrl+k`)

image
^ cursor still sat where `6` would have been, but `5` also cropped (after `ctrl+k`)

This might just be me misunderstanding `ctrl+k` or some weird symptom of different terminal emulators behaving differently.

**Comment by orefalo** [comment]
Interesting...

I am using iterm3/OSX and it works like a charm - similar to bash or fish shells.
with the current implementation on master,  it does not erase the first character on the line

this is with the fix
CleanShot 2023-06-21 at 06 30 26

CleanShot 2023-06-21 at 06 31 00

**Comment by orefalo** [comment]
and this is master

CleanShot 2023-06-21 at 06 33 07

CleanShot 2023-06-21 at 06 33 36

**Comment by lmorg** [comment]
ahhh I see the problem. it is an offset error with `ctrl+a`:
```
rl.line.SetCellPos(1)
rl.echo()
```
should read
```
rl.line.SetCellPos(0)
rl.echo()
moveCursorForwards(1)
```
line: https://github.com/lmorg/murex/blob/50630a52ac9905481ab8a94577b5a272324309e5/utils/readline/hotkey_functions.go#L8

It doesn't help that `rl.echo()` isn't putting the cursor on the right cell. I need to investigate that one further too.

**Comment by orefalo** [comment]
good
with your agreement, I will therefore close this PR.
from what I got, it's not fixing the core of the problem.

**Comment by laurence-flwls** [comment]
@orefalo fine to close. The question is whether you want me to raise the PR for the above change or do you fancy doing it?

**Comment by lmorg** [comment]
@orefalo fine to close. The question is whether you want me to raise the PR for the above change or do you fancy doing it? I'm happy either way but do really value your contributions (even this PR was helpful in finding the `ctrl+a` issue)

**Comment by orefalo** [comment]
plz fix it.
I will do the round() probably tomorrow

**Pull request closed without merging**
