### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by orefalo**

### CODE REVIEW

**Comment by orefalo** [comment]
I wonder if beyond renaming the category in the page… I should also move the page.

**Comment by orefalo** [comment]
give me some time, not working yet

**Comment by lmorg** [comment]
yeah, unfortunately the document ID isn't unique across categories (that would have been too sensible 😆 ) which means porting docs to different categories is a lot more painful than it should be :(

**Comment by orefalo** [comment]
I can confirm it's a pain...

Question, I think I got pretty much everything but ONE point.

How come:
```
  Related:
    - index
```

relates to:

```
- DocumentID: item-index
```
---


why is it not

```
  Related:
    - item-index
```

**Comment by lmorg** [comment]
That works because `commands/item-index` has `index` as a synonym.
It was originally just named `index` but i had to rename it due to vuepress treating index pages as category pages (makes sense really) and if truth be told, i was surprised that Docgen worked with that rename...and I wrote Docgen 😵‍💫

**Pull request closed without merging**
