### PR TITLE
'command:' - take 3

### PR DESCRIPTION
**Pull request by orefalo**
I hope this one will be the last...

A bit lost about content to be honest, maybe some files shouldn't be put into source control in the first place: ie. viewpress, docgen

### CODE REVIEW

**Comment by lmorg** [comment]
Nothing in `docs` should be edited directly because that all gets automatically generated. I like to have the docs in source control because it means if anyone clones the repo they have access to those docs. It also makes those docs available in Github too. Plus I've seen some package maintainers install murex docs into the OSs docs directory (eg https://www.freshports.org/shells/murex).

docgen and vuepress are code so makes sense them being tracked in source control.  Unless I'm misunderstanding you.

Is there a way you can turn off your markdown reformatting plugin? It's pushing quite an opinionated format of these markdown documents and I'm not convinced it enhances the readability of those documents when viewed as text (ie not compiled into HTML)

**Comment by orefalo** [comment]
If I may propose a better idea for the formatting.
implement proper formatting in the CICD pipeline

it's all implemented on one of my repos- https://github.com/orefalo/svelte-splitpanes

I can copy/paste if you would like.

-> of course, this doesn't mean you will like the formatted MD ;-)

**Comment by lmorg** [comment]
The formatting would then need to be written back to the git repository though. Which would then run the risk of constant merge conflicts. Presently _some_ of the formatting happens as part of the git commit hook. Admittedly a process I haven't shared with you yet.

**Comment by orefalo** [comment]
The linting stage check happens server **and client** sides. 
This ensures that all files that get checked-in comply to the project standards.

from your comment above, you may have similar checks -
The commit will fail if the files are not to standards. We have special npm script targets to lint and format files.
We use a combination of npm tools to enforce the above, namely 'lint-staged', 'husky', 'cz-customizable'

not sure if there are equivalents in the golang landscape and if you would be open to a project with mixed tech.

```
# .lintstagedrc
{
	"*.{js,ts,svelte,json,md}": [
		"prettier --ignore-path .gitignore --write --cache --plugin-search-dir=. !./pnpm-lock.yaml !./CHANGELOG.md",
		"eslint --cache --ignore-path .gitignore"
	],
	"*.{cjs,yml,yaml,lintstagedrc}": "prettier --ignore-path .gitignore --write --cache --plugin-search-dir=. !./pnpm-lock.yaml !./CHANGELOG.md"
}
```

to be fair, the flip side is that it can be a pain sometimes to commit a simple change.
  it's strong code governance vs flexibility

anyways, not trying to force anything - just saying that as the number of contributors raises, you will need to put something in place to enforce governance.

We can happy skip for now,

**Comment by lmorg** [comment]
We aren’t talking about source files though. The issue isn’t the Go files (which already are linted), it’s markdown files. And markdown files are, I’m my opinion, meant to be human readable first and machine readable second (otherwise we’d just be writing raw HTML, RTF, TROFF or other structured formats). Hence my concern with your markdown tool, it’s reformatting the files to follow a strict machine format when before they were structured to maximise human readability. In my opinion markdown files should never be machine linted (source code definitely, and markdown can be machine generated, but markdown shouldn’t be reformatted by a linter). 

The reason markdown was picked for documentation was because it can look good as raw text in the terminal but it’s also really easy to compile to HTML as well. In fact command line tools have followed a format that’s akin to markdown for years before markdown was ever coined as a term. I’ve spent most of the last 30 years on UNIX and similar systems with little more than a README and INSTALL file and only vi to read them in - and while I do want to modernise command line usage, there will be a lot of old nerds like me who will still follow this habit of reading documentation in the command line. So that use case needs to be supported as well as the website. 

As an aside, This is also the reason indentation was originally used for code instead of three backticks: indentation is more readable in the command line. I’m willing to make some concessions for the sake of getting the website to work but I just want to be mindful that the markdown files don’t get relegated to just another source file. 

It’s also worth noting that good text only documentation is a life saver in emergency situations like when X fails, the internet fails.

**Comment by lmorg** [comment]
It’s also worth noting that there’s a general rule of software development that formatting changes shouldn’t be included in the same PR as code changes.

Anyhow, I’ll still merge this PR (albeit tomorrow now) because there’s a lot of useful fixes in it. I can reformat the markdown in another commit after reviewing them if needed. The changes might not be as bad as the diff appears and it’s entirely possible I’m making an issue over nothing (I was just surprised to see so many formatting changes).

thanks for the work you’ve put into this. It is really appreciated

**Comment by orefalo** [comment]
right on spot: 'raw md'. Indeed my use cases around md are rendered outputs.

fine. 
should i just kill this PR?

**Comment by orefalo** [comment]
Arf i just realized you merged it in. 
will turn off my formatter

**Comment by lmorg** [comment]
> Arf i just realized you merged it in. will turn off my formatter

Yeah, I re-read my messages and was worried I was just coming off as grumpy. So I deleted them and just merged the PR. Sorry if you did find the tone of those messages off-putting. I really do appreciate your contributions.

**Pull request merged**
